/********************************************************************
* .h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error .h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtable();
extern void G__cpp_setup_inheritance();
extern void G__cpp_setup_typetable();
extern void G__cpp_setup_memvar();
extern void G__cpp_setup_global();
extern void G__cpp_setup_memfunc();
extern void G__cpp_setup_func();
extern void G__set_cpp_environment();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "unpacker_wk.h"
#include "hldevent_wk.h"
#include "hldsubevent_wk.h"
#include "event_wk.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LN_TClass;
extern G__linked_taginfo G__LN_TBuffer;
extern G__linked_taginfo G__LN_TMemberInspector;
extern G__linked_taginfo G__LN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_TROOT;
extern G__linked_taginfo G__LN_HldSubEvent;
extern G__linked_taginfo G__LN_HldEvent;
extern G__linked_taginfo G__LN_HldEventcLcLstat;
extern G__linked_taginfo G__LN_HldEventcLcLEvtHdr;
extern G__linked_taginfo G__LN_HldEventcLcLSubEvtTable;
extern G__linked_taginfo G__LN_Unpacker;
extern G__linked_taginfo G__LN_Event;

/* STUB derived class for protected member access */
