/********************************************************************
* mydict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mydict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablemydict();
extern void G__cpp_setup_inheritancemydict();
extern void G__cpp_setup_typetablemydict();
extern void G__cpp_setup_memvarmydict();
extern void G__cpp_setup_globalmydict();
extern void G__cpp_setup_memfuncmydict();
extern void G__cpp_setup_funcmydict();
extern void G__set_cpp_environmentmydict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "unpacker_wk.h"
#include "hldevent_wk.h"
#include "hldsubevent_wk.h"
#include "event_wk.h"
#include "eventhdr_wk.h"
#include "hit_wk.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mydictLN_TClass;
extern G__linked_taginfo G__mydictLN_TBuffer;
extern G__linked_taginfo G__mydictLN_TMemberInspector;
extern G__linked_taginfo G__mydictLN_TObject;
extern G__linked_taginfo G__mydictLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__mydictLN_string;
extern G__linked_taginfo G__mydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mydictLN_TClonesArray;
extern G__linked_taginfo G__mydictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mydictLN_TFile;
extern G__linked_taginfo G__mydictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__mydictLN_HldSubEvent;
extern G__linked_taginfo G__mydictLN_stat;
extern G__linked_taginfo G__mydictLN_HldEvent;
extern G__linked_taginfo G__mydictLN_HldEventcLcLEvtHdr;
extern G__linked_taginfo G__mydictLN_HldEventcLcLSubEvtTable;
extern G__linked_taginfo G__mydictLN_Unpacker;
extern G__linked_taginfo G__mydictLN_EventHdr;
extern G__linked_taginfo G__mydictLN_Hit;
extern G__linked_taginfo G__mydictLN_Event;

/* STUB derived class for protected member access */
